export const USER_APPS_REQUEST = 'USER_APPS_REQUEST';
export const USER_APPS_SUCCESS = 'USER_APPS_SUCCESS';
export const USER_APPS_FAIL = 'USER_APPS_FAIL';
export const USER_APPS_RESET = 'USER_APPS_RESET';

export const POST_APP_REQUEST = 'POST_APP_REQUEST';
export const POST_APP_SUCCESS = 'POST_APP_SUCCESS';
export const POST_APP_FAIL = 'POST_APP_FAIL';
export const POST_APP_RESET = 'POST_APP_RESET';

export const UPDATE_APP_REQUEST = 'UPDATE_APP_REQUEST';
export const UPDATE_APP_SUCCESS = 'UPDATE_APP_SUCCESS';
export const UPDATE_APP_FAIL = 'UPDATE_APP_FAIL';
export const UPDATE_APP_RESET = 'UPDATE_APP_RESET';

export const APP_TOOL_TIP_OFF = 'APP_TOOL_TIP_OFF';
export const APP_TOOL_TIP_ON = 'APP_TOOL_TIP_ON';
