export const POST_NOTE_REQUEST = 'POST_NOTE_REQUEST';
export const POST_NOTE_SUCCESS = 'POST_NOTE_SUCCESS';
export const POST_NOTE_FAIL = 'POST_NOTE_FAIL';
export const POST_NOTE_RESET = 'POST_NOTE_RESET';
