let colors = {
  white: 'white',
  red: 'red',
  salmon: 'salmon',
  orange: 'orange',
  gold: 'gold',
  yellow: 'yellow',
  lightGreen: 'light-green',
  green: 'green',
  darkGreen: 'dark-green',
  blueGreen: 'blue-green',
  lightBlue: 'light-blue',
  blue: 'blue',
  navy: 'navy',
  purple: 'purple',
  black: 'black',
  gray: 'gray',
  offPurple: 'off-purple',
};

export let colorsArr = [
  'default',
  'dark-1',
  'dark-2',
  'light-3',
  'light-2',
  'light-1',
  'row-1-1',
  'row-1-2',
  'row-1-3',
  'row-1-4',
  'row-1-5',
  'row-1-6',
  'row-2-1',
  'row-2-2',
  'row-2-3',
  'row-2-4',
  'row-2-5',
  'row-2-6',
  'row-3-1',
  'row-3-2',
  'row-3-3',
  'row-3-4',
  'row-3-5',
  'row-3-6',
  'row-4-1',
  'row-4-2',
  'row-4-3',
  'row-4-4',
  'row-4-5',
  'row-4-6',
  'row-5-1',
  'row-5-2',
  'row-5-3',
  'row-5-4',
  'row-5-5',
  'row-5-6',
  'row-6-1',
  'row-6-2',
  'row-6-3',
  'row-6-4',
  'row-6-5',
  'row-6-6',
];
export default colors;
